import express from "express";
import { ObjectId } from "mongodb";
import { fromNodeHeaders } from "better-auth/node";
import { auth } from "../lib/auth.js";
import { getCollections } from "../config/db.js";
import { verifyAuth } from "../middlewares/verifyAuth.js";
import { verifyRole } from "../middlewares/verifyRole.js";
import { sanitizeUser } from "../utils/sanitizeUser.js";
const router=express.Router();
const conditions=['Used','Like New','Refurbished']; const statuses=['pending','available','rejected','sold']; const oid=id=>ObjectId.isValid(id); const eq=(a,b)=>String(a)===String(b);
function userId(u){ const id=u?._id||u?.id; return id&&ObjectId.isValid(id)?new ObjectId(id):id; }
function slug(t){ return t.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-'); }
function multi(v){ if(!v) return []; return (Array.isArray(v)?v:[v]).flatMap(x=>String(x).split(',').map(s=>s.trim()).filter(Boolean)); }
function validate(p,mode='create'){ const e=[]; if(mode==='create'&&!p.title?.trim()) e.push('Product title is required.'); if(p.title&&p.title.trim().length<3) e.push('Product title must be at least 3 characters.'); if(mode==='create'&&!p.category?.trim()) e.push('Product category is required.'); if(p.condition&&!conditions.includes(p.condition)) e.push('Condition must be Used, Like New, or Refurbished.'); if(mode==='create'&&!p.condition) e.push('Product condition is required.'); if(p.price!==undefined&&(Number.isNaN(Number(p.price))||Number(p.price)<=0)) e.push('Product price must be greater than 0.'); if(mode==='create'&&p.price===undefined) e.push('Product price is required.'); if(p.stockQuantity!==undefined&&(Number.isNaN(Number(p.stockQuantity))||Number(p.stockQuantity)<0)) e.push('Stock quantity cannot be negative.'); if(mode==='create'&&(!Array.isArray(p.images)||!p.images.length)) e.push('At least one product image URL is required.'); if(p.images!==undefined&&(!Array.isArray(p.images)||p.images.some(x=>typeof x!=='string'||!x.startsWith('http')))) e.push('Each image must be a valid URL.'); if(mode==='create'&&!p.description?.trim()) e.push('Product description is required.'); if(p.description&&p.description.trim().length<10) e.push('Description must be at least 10 characters.'); if(mode==='create'&&!p.location?.trim()) e.push('Product location is required.'); return e; }
function publicQuery({search,category,condition,minPrice,maxPrice,location}){ const q={status:'available'}; if(search) q.$or=[{title:{$regex:search,$options:'i'}},{category:{$regex:search,$options:'i'}},{description:{$regex:search,$options:'i'}},{location:{$regex:search,$options:'i'}}]; const cats=multi(category); if(cats.length) q.category={$in:cats}; const cons=multi(condition); if(cons.length) q.condition={$in:cons}; if(location) q.location={$regex:location,$options:'i'}; const price={}; if(minPrice!==undefined&&minPrice!==''&&!Number.isNaN(Number(minPrice))) price.$gte=Number(minPrice); if(maxPrice!==undefined&&maxPrice!==''&&!Number.isNaN(Number(maxPrice))) price.$lte=Number(maxPrice); if(Object.keys(price).length) q.price=price; return q; }
function sortBy(s){ if(s==='price-asc') return {price:1}; if(s==='price-desc') return {price:-1}; if(s==='oldest') return {createdAt:1}; return {createdAt:-1}; }
function dashboardQuery({search,status,category}){ const q={}; if(search) q.$or=[{title:{$regex:search,$options:'i'}},{category:{$regex:search,$options:'i'}},{location:{$regex:search,$options:'i'}},{'sellerInfo.name':{$regex:search,$options:'i'}},{'sellerInfo.email':{$regex:search,$options:'i'}}]; if(status&&statuses.includes(status)) q.status=status; if(category) q.category=category; return q; }
async function optionalUser(req){ try{ const session=await auth.api.getSession({headers:fromNodeHeaders(req.headers)}); if(!session?.user?.email) return null; const {usersCollection}=getCollections(); const u=await usersCollection.findOne({email:session.user.email}); if(!u||u.status==='blocked') return null; return sanitizeUser(u); }catch{return null;} }
router.get('/seller/my-products',verifyAuth,verifyRole('seller'),async(req,res,next)=>{try{ const {search='',status='',category='',page=1,limit=10}=req.query; const pageNumber=Math.max(Number(page)||1,1), limitNumber=Math.min(Math.max(Number(limit)||10,1),50), skip=(pageNumber-1)*limitNumber; const q={...dashboardQuery({search,status,category}),'sellerInfo.userId':userId(req.user)}; const {productsCollection}=getCollections(); const [products,total]=await Promise.all([productsCollection.find(q).sort({createdAt:-1}).skip(skip).limit(limitNumber).toArray(),productsCollection.countDocuments(q)]); res.json({success:true,total,page:pageNumber,limit:limitNumber,totalPages:Math.ceil(total/limitNumber),products});}catch(e){next(e)}});
router.get('/admin/all',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ const {search='',status='',category='',page=1,limit=10}=req.query; const pageNumber=Math.max(Number(page)||1,1), limitNumber=Math.min(Math.max(Number(limit)||10,1),50), skip=(pageNumber-1)*limitNumber; const q=dashboardQuery({search,status,category}); const {productsCollection}=getCollections(); const [products,total]=await Promise.all([productsCollection.find(q).sort({createdAt:-1}).skip(skip).limit(limitNumber).toArray(),productsCollection.countDocuments(q)]); res.json({success:true,total,page:pageNumber,limit:limitNumber,totalPages:Math.ceil(total/limitNumber),products});}catch(e){next(e)}});
router.post('/',verifyAuth,verifyRole('seller'),async(req,res,next)=>{try{ const errors=validate(req.body,'create'); if(errors.length) return res.status(400).json({success:false,message:errors[0],errors}); const {title,category,condition,price,stockQuantity=1,images,description,location}=req.body; const product={title:title.trim(),slug:`${slug(title)}-${Date.now()}`,category:category.trim(),condition,price:Number(price),stockQuantity:Number(stockQuantity),images:images.map(x=>x.trim()).filter(Boolean),description:description.trim(),location:location.trim(),sellerInfo:{userId:userId(req.user),name:req.user.name,email:req.user.email,phone:req.user.phone||'',photo:req.user.photo||req.user.image||'',isVerifiedSeller:Boolean(req.user.isVerifiedSeller)},status:'pending',rejectionReason:'',reportCount:0,views:0,createdAt:new Date(),updatedAt:new Date()}; const {productsCollection}=getCollections(); const result=await productsCollection.insertOne(product); res.status(201).json({success:true,message:'Product created successfully and waiting for admin approval.',productId:result.insertedId});}catch(e){next(e)}});
router.get('/',async(req,res,next)=>{try{ const {search='',category='',condition='',minPrice='',maxPrice='',location='',sort='newest',page=1,limit=12}=req.query; const pageNumber=Math.max(Number(page)||1,1), limitNumber=Math.min(Math.max(Number(limit)||12,1),60), skip=(pageNumber-1)*limitNumber; const q=publicQuery({search,category,condition,minPrice,maxPrice,location}); const {productsCollection}=getCollections(); const [products,total]=await Promise.all([productsCollection.find(q).sort(sortBy(sort)).skip(skip).limit(limitNumber).toArray(),productsCollection.countDocuments(q)]); res.json({success:true,count:products.length,total,page:pageNumber,limit:limitNumber,totalPages:Math.ceil(total/limitNumber),products});}catch(e){next(e)}});
router.get('/featured',async(req,res,next)=>{try{ const limitNumber=Math.min(Math.max(Number(req.query.limit)||8,1),12); const {productsCollection}=getCollections(); const products=await productsCollection.find({status:'available'}).sort({createdAt:-1}).limit(limitNumber).toArray(); res.json({success:true,count:products.length,products}); }catch(e){next(e)}});
router.get('/categories',async(req,res,next)=>{try{ const {productsCollection}=getCollections(); const categories=await productsCollection.distinct('category',{status:'available'}); const fallback=['Electronics','Mobile Phones','Furniture','Vehicles','Fashion','Home Appliances','Books','Sports','Gaming','Others']; res.json({success:true,categories:categories.length?categories:fallback});}catch(e){next(e)}});
router.get('/:id',async(req,res,next)=>{try{ if(!oid(req.params.id)) return res.status(400).json({success:false,message:'Invalid product id.'}); const {productsCollection}=getCollections(); const product=await productsCollection.findOne({_id:new ObjectId(req.params.id)}); if(!product) return res.status(404).json({success:false,message:'Product not found.'}); if(product.status==='available') return res.json({success:true,product}); const u=await optionalUser(req); const isOwner=u&&eq(product.sellerInfo?.userId,userId(u)); const isAdmin=u?.role==='admin'; if(!isOwner&&!isAdmin) return res.status(403).json({success:false,message:'This product is not publicly available.'}); res.json({success:true,product});}catch(e){next(e)}});
router.patch('/:id',verifyAuth,verifyRole('seller'),async(req,res,next)=>{try{ if(!oid(req.params.id)) return res.status(400).json({success:false,message:'Invalid product id.'}); const errors=validate(req.body,'update'); if(errors.length) return res.status(400).json({success:false,message:errors[0],errors}); const {productsCollection}=getCollections(); const product=await productsCollection.findOne({_id:new ObjectId(req.params.id)}); if(!product) return res.status(404).json({success:false,message:'Product not found.'}); if(!eq(product.sellerInfo?.userId,userId(req.user))) return res.status(403).json({success:false,message:'You can update only your own products.'}); if(product.status==='sold') return res.status(400).json({success:false,message:'Sold product cannot be updated.'}); const allowed=['title','category','condition','price','stockQuantity','images','description','location']; const set={updatedAt:new Date()}; for(const f of allowed){ if(req.body[f]!==undefined){ if(f==='price'||f==='stockQuantity') set[f]=Number(req.body[f]); else if(f==='images') set[f]=req.body.images.map(x=>x.trim()).filter(Boolean); else if(typeof req.body[f]==='string') set[f]=req.body[f].trim(); else set[f]=req.body[f]; }} if(set.title) set.slug=`${slug(set.title)}-${Date.now()}`; await productsCollection.updateOne({_id:new ObjectId(req.params.id)},{$set:set}); res.json({success:true,message:'Product updated successfully.'});}catch(e){next(e)}});
router.delete('/:id',verifyAuth,verifyRole('seller'),async(req,res,next)=>{try{ if(!oid(req.params.id)) return res.status(400).json({success:false,message:'Invalid product id.'}); const {productsCollection}=getCollections(); const product=await productsCollection.findOne({_id:new ObjectId(req.params.id)}); if(!product) return res.status(404).json({success:false,message:'Product not found.'}); if(!eq(product.sellerInfo?.userId,userId(req.user))) return res.status(403).json({success:false,message:'You can delete only your own products.'}); if(product.status==='sold') return res.status(400).json({success:false,message:'Sold product cannot be deleted.'}); await productsCollection.deleteOne({_id:new ObjectId(req.params.id)}); res.json({success:true,message:'Product deleted successfully.'});}catch(e){next(e)}});
router.patch('/:id/approve',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ if(!oid(req.params.id)) return res.status(400).json({success:false,message:'Invalid product id.'}); const {productsCollection}=getCollections(); const result=await productsCollection.updateOne({_id:new ObjectId(req.params.id)},{$set:{status:'available',rejectionReason:'',updatedAt:new Date()}}); if(!result.matchedCount) return res.status(404).json({success:false,message:'Product not found.'}); res.json({success:true,message:'Product approved successfully.'});}catch(e){next(e)}});
router.patch('/:id/reject',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ const {rejectionReason}=req.body; if(!oid(req.params.id)) return res.status(400).json({success:false,message:'Invalid product id.'}); if(!rejectionReason?.trim()) return res.status(400).json({success:false,message:'Rejection reason is required.'}); const {productsCollection}=getCollections(); const result=await productsCollection.updateOne({_id:new ObjectId(req.params.id)},{$set:{status:'rejected',rejectionReason:rejectionReason.trim(),updatedAt:new Date()}}); if(!result.matchedCount) return res.status(404).json({success:false,message:'Product not found.'}); res.json({success:true,message:'Product rejected successfully.'});}catch(e){next(e)}});
router.delete('/:id/admin',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ if(!oid(req.params.id)) return res.status(400).json({success:false,message:'Invalid product id.'}); const {productsCollection}=getCollections(); const result=await productsCollection.deleteOne({_id:new ObjectId(req.params.id)}); if(!result.deletedCount) return res.status(404).json({success:false,message:'Product not found.'}); res.json({success:true,message:'Product removed by admin.'});}catch(e){next(e)}});
export default router;
