import express from "express";
import { ObjectId } from "mongodb";
import { getCollections } from "../config/db.js";
import { verifyAuth } from "../middlewares/verifyAuth.js";
import { verifyRole } from "../middlewares/verifyRole.js";
import { sanitizeUser } from "../utils/sanitizeUser.js";
const router=express.Router();
const statuses=['active','blocked']; const roles=['buyer','seller','admin'];
const oid=id=>ObjectId.isValid(id);
function q({search,role,status}){ const query={}; if(search) query.$or=[{name:{$regex:search,$options:'i'}},{email:{$regex:search,$options:'i'}},{phone:{$regex:search,$options:'i'}},{location:{$regex:search,$options:'i'}}]; if(role&&roles.includes(role)) query.role=role; if(status&&statuses.includes(status)) query.status=status; return query; }
router.get('/profile',verifyAuth,(req,res)=>res.json({success:true,user:req.user}));
router.patch('/profile',verifyAuth,async(req,res,next)=>{try{ const {name,phone,location,photo,image}=req.body; const set={updatedAt:new Date()}; if(typeof name==='string') set.name=name.trim(); if(typeof phone==='string') set.phone=phone.trim(); if(typeof location==='string') set.location=location.trim(); if(typeof photo==='string'){set.photo=photo.trim(); set.image=photo.trim();} if(typeof image==='string'){set.image=image.trim(); set.photo=image.trim();} const {usersCollection}=getCollections(); const result=await usersCollection.updateOne({email:req.user.email},{$set:set}); if(!result.matchedCount) return res.status(404).json({success:false,message:'User profile not found.'}); const user=await usersCollection.findOne({email:req.user.email}); res.json({success:true,message:'Profile updated successfully.',user:sanitizeUser(user)});}catch(e){next(e)}});
router.patch('/become-seller',verifyAuth,async(req,res,next)=>{try{ if(req.user.role==='admin') return res.status(400).json({success:false,message:'Admin account cannot be converted to seller.'}); if(req.user.role==='seller') return res.json({success:true,message:'You are already a seller.',role:'seller'}); const {phone,location}=req.body; if(!phone||!location) return res.status(400).json({success:false,message:'Phone and location are required to become a seller.'}); const {usersCollection}=getCollections(); await usersCollection.updateOne({email:req.user.email},{$set:{role:'seller',phone:phone.trim(),location:location.trim(),updatedAt:new Date()}}); res.json({success:true,message:'You are now a seller.',role:'seller'}); }catch(e){next(e)}});
router.get('/',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ const {search='',role='',status='',page=1,limit=10}=req.query; const pageNumber=Math.max(Number(page)||1,1), limitNumber=Math.min(Math.max(Number(limit)||10,1),50), skip=(pageNumber-1)*limitNumber; const query=q({search,role,status}); const {usersCollection}=getCollections(); const [users,total]=await Promise.all([usersCollection.find(query,{projection:{password:0}}).sort({createdAt:-1}).skip(skip).limit(limitNumber).toArray(), usersCollection.countDocuments(query)]); res.json({success:true,total,page:pageNumber,limit:limitNumber,totalPages:Math.ceil(total/limitNumber),users:users.map(sanitizeUser)});}catch(e){next(e)}});
router.patch('/:id/status',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ const {id}=req.params,{status}=req.body; if(!oid(id)) return res.status(400).json({success:false,message:'Invalid user id.'}); if(!statuses.includes(status)) return res.status(400).json({success:false,message:'Invalid user status.'}); if(req.user._id===id||req.user.id===id) return res.status(400).json({success:false,message:'You cannot update your own status.'}); const {usersCollection}=getCollections(); const target=await usersCollection.findOne({_id:new ObjectId(id)}); if(!target) return res.status(404).json({success:false,message:'User not found.'}); if(target.role==='admin') return res.status(403).json({success:false,message:'Another admin account cannot be blocked.'}); await usersCollection.updateOne({_id:new ObjectId(id)},{$set:{status,updatedAt:new Date()}}); res.json({success:true,message:`User has been ${status}.`}); }catch(e){next(e)}});
router.patch('/:id/verify-seller',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ const {id}=req.params,{isVerifiedSeller}=req.body; if(!oid(id)) return res.status(400).json({success:false,message:'Invalid user id.'}); if(typeof isVerifiedSeller!=='boolean') return res.status(400).json({success:false,message:'isVerifiedSeller must be true or false.'}); const {usersCollection,productsCollection}=getCollections(); const seller=await usersCollection.findOne({_id:new ObjectId(id)}); if(!seller) return res.status(404).json({success:false,message:'Seller not found.'}); if(seller.role!=='seller') return res.status(400).json({success:false,message:'Only seller accounts can be verified.'}); await usersCollection.updateOne({_id:new ObjectId(id)},{$set:{isVerifiedSeller,updatedAt:new Date()}}); await productsCollection.updateMany({'sellerInfo.userId':new ObjectId(id)},{$set:{'sellerInfo.isVerifiedSeller':isVerifiedSeller,updatedAt:new Date()}}); res.json({success:true,message:isVerifiedSeller?'Seller verified successfully.':'Seller verification removed successfully.'}); }catch(e){next(e)}});
router.delete('/:id',verifyAuth,verifyRole('admin'),async(req,res,next)=>{try{ const {id}=req.params; if(!oid(id)) return res.status(400).json({success:false,message:'Invalid user id.'}); if(req.user._id===id||req.user.id===id) return res.status(400).json({success:false,message:'You cannot delete your own account.'}); const {usersCollection}=getCollections(); const target=await usersCollection.findOne({_id:new ObjectId(id)}); if(!target) return res.status(404).json({success:false,message:'User not found.'}); if(target.role==='admin') return res.status(403).json({success:false,message:'Admin account cannot be deleted from this panel.'}); await usersCollection.deleteOne({_id:new ObjectId(id)}); res.json({success:true,message:'User deleted successfully.'}); }catch(e){next(e)}});
export default router;
